# Generated by Django 4.1.7 on 2023-03-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_preview',
            new_name='image',
        ),
    ]
