# Generated by Django 4.1.7 on 2023-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_image_preview_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='product_quantity',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='size',
            new_name='product_size',
        ),
        migrations.AlterField(
            model_name='clothingsize',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, null=True),
        ),
    ]
