# Generated by Django 4.1.7 on 2023-03-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_inventory_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'product_size')},
        ),
    ]
